name:
  r_rmd_pekowska2019
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-biocmanager
  - r-rmarkdown
  # - r-bookdown
  # - pandoc=1.19 #requirement to render R Markdown.
  - r-codetools #requirement to avoid error after first R chunk during R Markdown rendering.
  - bioconductor-geoquery # can not be installed through BiocManager
  # NOTE: commented tools to try to avoid conda conflict dependencies
  # Installing with BiocManager instead of conda avoid also an error when creating a topGO object
  #- bioconductor-rtracklayer
  #- bioconductor-biomart
  #- bioconductor-topgo
  #- r-data.table
  #- bioconductor-gviz
  #- r-stringr
  #- bioconductor-ensdb.hsapiens.v86
  #- r-venndiagram
  #- bioconductor-go.db
  #- bioconductor-ensembldb
  # Dependencies for GOBP_Chen_Broad.R script seems to be conflicting with requirements for Pekowska_et_al_Mol_Cell.Rmd
  # - bioconductor-org.hs.eg.db == 3.5
  # - bioconductor-clusterprofiler
  # - bioconductor-complexheatmap
  # - r-reshape2
  # - r-circlize
