name:
  r_pekowska2019
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-org.hs.eg.db == 3.5
  - bioconductor-clusterprofiler
  - bioconductor-complexheatmap
  - r-reshape2
  - r-circlize
